# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

spring:
  data:
    mongodb:
      username: test
      password: test
      host: localhost
      port: 27017
      database: searching
      authentication-database: admin